title: Hype of Data Science 
author: mondtorsha
email: torsha.mond333@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 This is my first website hosted by GitHub. I dedicate this website to talk about hype of Data Science
 

# social links

github_username:  https://github.com/mondtorsha # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
